version: 0.2

env:
  variables:
    ECR_REPO_NAME: user-service
    REGION: ap-south-1
    CLUSTER_NAME: betterwellness-cluster

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging into ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Getting frontend URL from SSM...
      - FRONTEND_URL=$(aws ssm get-parameter --name "/betterwellness/frontend/url" --region $REGION --with-decryption --query Parameter.Value --output text)
      - echo Updating CORS config...
      - sed -i "s|setAllowedOrigins(.*)|setAllowedOrigins(List.of(\"$FRONTEND_URL\"))|g" src/main/java/com/betterwellness/userservice/config/CorsConfig.java
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
      - echo Replacing image URI in k8s.yaml...
      - sed -i "s|<IMAGE_URI>|$REPOSITORY_URI:$IMAGE_TAG|g" k8s.yaml
      - echo "Final k8s.yaml contents:"
      - cat k8s.yaml
      - echo Applying Kubernetes manifest...
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
      - kubectl apply -f k8s.yaml

artifacts:
  files: '**/*'
